# Welcome to Jekyll!
#

# Site settings
title: Bella Taylor
description: |
  Web Developer
owner: Bella Taylor # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: bellataylorlondon@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bellataylor.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/djbellataylor
  github: https://github.com/BellaT
  linkedin-square: https://linkedin.com/in/bellataylorlondon
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  spotify: https://open.spotify.com/user/1116673725
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  soundcloud: https://soundcloud.com/bella-t
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
